# Generated by Django 4.2.3 on 2023-07-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
